#!/usr/bin/env bash

# if not interactive, stop
if [ -z "$PS1" ]; then
  return
fi

PATH="/usr/local/sbin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="$HOME/.cabal/bin:$PATH"
PATH="$HOME/local/bin:$PATH"
PATH="$HOME/bin:$PATH"
export PATH="$PATH"

export EDITOR="vim"

# cygwin style prompt, show git info
source ~/.dotfiles-config/git-prompt.sh
export PS1="\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[36m\]\$(__git_ps1 \"(%s) \")\[\e[33m\]\w\[\e[0m\]\n\$ "

if [ "$(uname)" = "Darwin" ]; then
  alias ls='ls -G'
else
  alias ls='ls --color=auto'
fi
alias ll='ls -lh'
alias la='ls -A'
alias lla='ls -lhA'

alias grep='grep --color=auto'

alias gs='git status'
alias gd='git diff'
alias gl='git log'
alias gb='git branch'
alias gwc='git whatchanged'
alias gco='git checkout'
alias gci='git commit'
alias gdc='git diff --cached'
alias gbv='git branch -a -vv'

alias ocaml='rlwrap ocaml'
alias ocamld='rlwrap ocamldebug'
alias ocamldebug='rlwrap ocamldebug'
alias coqtop='rlwrap coqtop'

alias ..='cd ..'

export PATH="$PATH:/usr/local/Cellar/smlnj/110.73/libexec/bin" # smlnj
export PATH="$PATH:/usr/local/Cellar/ruby/1.9.3-p194/bin"      # ruby gems
export KRAKEN="$HOME/kraken"                                   # kraken

source ~/.dotfiles-config/git-completions
source ~/.dotfiles-config/alias-completions

if [ "$(hostname)" = "goto" ]; then
  AGENT=/usr/bin/ssh-agent
  if [ -z "$SSH_AUTH_SOCK" -a -x "$AGENT" ]; then
    eval `$AGENT -s`
    trap "kill $SSH_AGENT_PID" 0
  fi
fi

echo
fortune.py
